// This file is auto-generated by scripts/generate-design-tokens.mjs
export const DESIGN_TOKENS = {
  fontFamily: {
    body: {
      medium: "Manrope-Medium",
      semiBold: "Manrope-SemiBold",
      bold: "Manrope-Bold"
    }
  },
  color: {
    canvas: {
      default: "#F5F8FD",
      elevated: "#FCFAF7"
    },
    surface: {
      default: "#FFFFFF",
      muted: "#F1EBE5",
      accent: "#F2EDFF",
      input: "#EFF2F7",
      inputActive: "#D4D4D4"
    },
    border: {
      default: "#E8ECEF",
      strong: "#D8CDC2"
    },
    text: {
      primary: "#17131A",
      secondary: "#6F6470",
      muted: "#9A8F98",
      subtle: "#68727D",
      placeholder: "#57626F",
      disabled: "#DCDCDD",
      tertiary: "#A3A3A3",
      inverse: "#FFFFFF"
    },
    brand: {
      primary: "#6115CD",
      strong: "#5831E8",
      soft: "#EEE7FF",
      pressed: "#4E11A4",
      pressedText: "#DFD0F5",
      disabled: "#D5C9FF"
    },
    action: {
      default: "#FF2B75",
      hover: "#EA276B",
      active: "#DE2465",
      disabled: "#FFBAD2"
    },
    feedback: {
      success: {
        surface: "#DDF7E7",
        text: "#1C6B45"
      },
      warning: {
        surface: "#FEF3C7",
        text: "#92400E"
      },
      danger: {
        surface: "#FDE9EF",
        text: "#B43B69"
      },
      like: {
        surface: "#FFEAF1",
        icon: "#F43F5E"
      },
      skeleton: "#E5E7EB"
    },
    overlay: {
      soft: "rgba(23, 19, 26, 0.04)",
      medium: "rgba(16, 16, 22, 0.52)"
    }
  },
  radius: {
    sm: 14,
    md: 18,
    lg: 24,
    xl: 28,
    full: 999
  },
  size: {
    layout: {
      screenPadding: 20,
      sectionGap: 20
    },
    card: {
      radius: 24
    },
    avatar: {
      md: 44
    },
    post: {
      coverHeight: 220
    }
  }
} as const;
