// This file is auto-generated by scripts/generate-design-tokens.mjs
export const DEFAULT_THEME = "light" as const;
export const DESIGN_TOKENS = {
  foundation: {
    fontFamily: {
      body: {
        medium: "Manrope-Medium",
        semiBold: "Manrope-SemiBold",
        bold: "Manrope-Bold"
      }
    },
    space: {
      xxs: 4,
      xs: 8,
      sm: 12,
      md: 16,
      lg: 20,
      xl: 24,
      xxl: 28,
      xxxl: 32,
      control: 40,
      avatar: 44
    },
    radius: {
      sm: 14,
      md: 18,
      input: 20,
      lg: 24,
      xl: 28,
      full: 999
    },
    typography: {
      xs: {
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 0
      },
      sm: {
        fontSize: 13,
        lineHeight: 18,
        letterSpacing: 0
      },
      md: {
        fontSize: 15,
        lineHeight: 20,
        letterSpacing: 0
      },
      lg: {
        fontSize: 18,
        lineHeight: 26,
        letterSpacing: 0
      },
      xl: {
        fontSize: 32,
        lineHeight: 40,
        letterSpacing: -0.8
      }
    },
    borderWidth: {
      thin: 1,
      medium: 2
    },
    size: {
      avatar: {
        sm: 40,
        md: 44
      },
      control: {
        sm: 40,
        md: 42
      },
      icon: {
        sm: 16,
        md: 18,
        lg: 20
      },
      post: {
        coverHeight: 220
      }
    },
    opacity: {
      disabled: 0.45,
      muted: 0.7
    }
  },
  semantic: {
    light: {
      color: {
        canvas: {
          default: "#F5F8FD",
          elevated: "#FCFAF7"
        },
        surface: {
          default: "#FFFFFF",
          muted: "#F1EBE5",
          accent: "#F2EDFF",
          input: "#EFF2F7",
          inputActive: "#D4D4D4"
        },
        border: {
          default: "#E8ECEF",
          strong: "#D8CDC2"
        },
        text: {
          primary: "#111416",
          secondary: "#6F6470",
          stat: "#57626F",
          muted: "#9A8F98",
          subtle: "#68727D",
          placeholder: "#57626F",
          disabled: "#DCDCDD",
          tertiary: "#A3A3A3",
          inverse: "#FFFFFF"
        },
        brand: {
          primary: "#6115CD",
          strong: "#5831E8",
          soft: "#EEE7FF",
          pressed: "#4E11A4",
          pressedText: "#DFD0F5",
          disabled: "#D5C9FF"
        },
        action: {
          default: "#FF2B75",
          hover: "#EA276B",
          active: "#DE2465",
          disabled: "#FFBAD2"
        },
        feedback: {
          success: {
            surface: "#DDF7E7",
            text: "#1C6B45"
          },
          warning: {
            surface: "#FEF3C7",
            text: "#92400E"
          },
          danger: {
            surface: "#FDE9EF",
            text: "#B43B69"
          },
          like: {
            surface: "#FFEAF1",
            icon: "#F43F5E"
          },
          skeleton: "#E5E7EB"
        },
        overlay: {
          soft: "rgba(23, 19, 26, 0.04)",
          medium: "rgba(16, 16, 22, 0.52)"
        }
      }
    }
  },
  component: {
    layout: {
      screenPadding: 20,
      sectionGap: 20,
      contentGap: 14,
      cardPadding: 16,
      panelPadding: 20,
      floatingInset: 20,
      floatingOffset: 24,
      safeOffset: 12
    },
    card: {
      radius: 24
    },
    button: {
      radius: 14,
      size: {
        sm: {
          height: 40,
          paddingX: 14,
          paddingY: 10,
          gap: 8
        },
        md: {
          height: 42,
          paddingX: 32,
          paddingY: 10,
          gap: 8
        }
      }
    },
    input: {
      height: 40,
      heightMultiline: 44,
      paddingY: 10,
      paddingX: 16,
      gap: 6,
      borderWidth: 2,
      radius: 20
    },
    iconButton: {
      size: {
        sm: 40,
        md: 42
      }
    },
    sendButton: {
      size: {
        sm: 40,
        md: 42
      }
    },
    avatar: {
      size: {
        sm: 40,
        md: 44
      }
    },
    chip: {
      size: {
        sm: {
          gap: 4,
          paddingY: 6,
          paddingXLeading: 6,
          paddingXTrailing: 12
        },
        md: {
          gap: 8,
          paddingY: 12,
          paddingX: 16
        }
      }
    },
    segmentedControl: {
      itemPadding: 10
    },
    likeButton: {
      paddingX: 16,
      paddingY: 12,
      gap: 12,
      iconSize: 34
    },
    badge: {
      paddingX: 12,
      paddingY: 6
    },
    image: {
      postRadius: 28
    }
  }
} as const;
export type DesignThemeName = keyof typeof DESIGN_TOKENS.semantic;
